name = "MyModelMenagerie"
uuid = "7c35333e-f05c-485e-b6f6-27244a3c2401"
authors = ["Dhruva Venkita Raman"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
